# Generated by Django 5.0.1 on 2024-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
