# Generated by Django 5.0.1 on 2024-03-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
