# Generated by Django 5.0.1 on 2024-03-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='is_inhabited',
        ),
    ]
